export const HANDLE_OPEN_ROOM = 'HANDLE_OPEN_ROOM';
export const HANDLE_CHANGE_CHANNEL_ID = 'HANDLE_CHANGE_CHANNEL_ID';
export const HANDLE_SEND_NEW_MESSAGE = 'HANDLE_SEND_NEW_MESSAGE';
export const HANDLE_INC_NEW_MESSAGE = 'HANDLE_INC_NEW_MESSAGE';
export const HANDLE_CLOSE_ROOM = 'HANDLE_CLOSE_ROOM';
